### PR TITLE
Remove global namespace from API documentation

### PR DESCRIPTION
**Pull request by pascalberger**
Remove global namespace from API documentation

### CODE REVIEW

**Comment by gep13** [comment]
Interesting, I was looking for how to do this 😄

**Comment by pascalberger** [comment]
@gep13 I'm still looking for a way to get rid of the `Costura` namespace

**Comment by gep13** [comment]
I bet @daveaglick might know 😄

**Comment by daveaglick** [comment]
Easiest way I can think of is to add a new `Where` module at the end of the "Api" pipeline to act as a filter and strip out any symbols with that namespace. I've got this open *right now!* so I can put a PR together for that.

Out of curiosity, where is it coming from? Doesn't look like there's any types associated with it...

**Comment by pascalberger** [comment]
@daveaglick A PR would be awesome! It is created during build by [Fody Costura](https://github.com/Fody/Costura).

**Comment by daveaglick** [comment]
Ah, gotcha. Should have recognized the name.

**Pull request merged**
