### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by pascalberger**
Deploy build from master even without Tag, or without Tag recognized by AppVeyor (eg. from SourceTree)

### CODE REVIEW

**Comment by gep13** [comment]
@pascalberger interesting, is this something that needs to go back into Cake.Recipe?

**Comment by pascalberger** [comment]
@gep13 Not sure how it can be handled in a good way in Cake.Recipe. It seems like eg. SourceTree creates tags which AppVeyor doesn't recognize as tags compared if eg. a tag is created through GitHub website (I think the reason is that `base_ref` is not set in the webhook payload).

**Comment by gep13** [comment]
hmmm. Is this an issue in SourceTree or in AppVeyor then?

**Comment by pascalberger** [comment]
I would vote for GitHub or AppVeyor. The tag created by SourceTree obviously exists in the Git repo and is also shown in GitHub (https://github.com/cake-contrib/Cake.Prca.Website/releases/tag/0.3.0)

**Pull request merged**
